#!/usr/bin/env node
// Samples recent Hall dispatch audit artifacts, computes health metrics,
// and posts findings as a GitHub issue.
'use strict'

const { spawnSync } = require('child_process')
const { readFileSync, mkdirSync, rmSync, readdirSync, existsSync } = require('fs')
const { join } = require('path')

const REPO = process.env.REPO || process.env.GITHUB_REPOSITORY
const SAMPLE = parseInt(process.env.SAMPLE_SIZE || '50', 10)
const RUN_ID = process.env.GITHUB_RUN_ID || ''
const TMP = '/tmp/hall-stability'

function gh(...args) {
  const r = spawnSync('gh', args, { encoding: 'utf8' })
  if (r.status !== 0) throw new Error(`gh ${args.join(' ')}: ${r.stderr || r.stdout}`)
  return r.stdout.trim()
}

function ghJson(...args) {
  try { return JSON.parse(gh(...args)) } catch { return null }
}

function listRuns() {
  return ghJson(
    'run', 'list', '--repo', REPO,
    '--workflow', 'invoke.yml',
    '--limit', String(SAMPLE),
    '--json', 'databaseId,createdAt,conclusion'
  ) || []
}

function fetchLog(runId) {
  const dir = join(TMP, String(runId))
  mkdirSync(dir, { recursive: true })
  try {
    spawnSync('gh', ['run', 'download', String(runId), '--repo', REPO,
      '--dir', dir, '--pattern', 'hall-log-*'], { encoding: 'utf8' })
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue
      const p = join(dir, entry.name, 'hall-invocation-log.json')
      if (existsSync(p)) return JSON.parse(readFileSync(p, 'utf8'))
    }
  } catch { /* expired or missing artifact */ }
  return null
}

function pct(n, total) {
  return total > 0 ? `${((n / total) * 100).toFixed(1)}%` : '—'
}

function classify(log) {
  if (!log) return 'missing'
  const o = (log.outcome || '').toLowerCase()
  if (o === 'failed') return 'failed'
  if (o === 'quota_exceeded') return 'quota'
  if (o === 'max_turns_exceeded') return 'max_turns'
  if ((log.retry_count || 0) > 0) return 'refined'
  return 'success'
}

function buildBody(counts, total, dates, tokenInput, tokenOutput, tokenCount) {
  const oldest = dates.length ? dates[dates.length - 1].slice(0, 10) : '—'
  const newest = dates.length ? dates[0].slice(0, 10) : '—'
  const month = new Date().toLocaleString('default', { month: 'long', year: 'numeric' })

  const tokenSection = tokenCount > 0
    ? `| Avg input tokens/dispatch | ${Math.round(tokenInput / tokenCount).toLocaleString()} |\n` +
      `| Avg output tokens/dispatch | ${Math.round(tokenOutput / tokenCount).toLocaleString()} |\n` +
      `| Token-tracked dispatches | ${tokenCount} / ${total} |`
    : '_No token data — KR #181 not yet deployed._'

  return `## Hall Stability Report — ${month}\n\n**Sample:** last ${total} dispatches (${oldest} → ${newest})\n\n### Outcome breakdown\n\n| Outcome | Count | Rate |\n|---------|-------|------|\n| Completed | ${counts.success} | ${pct(counts.success, total)} |\n| Failed | ${counts.failed} | ${pct(counts.failed, total)} |\n| Quota exhausted | ${counts.quota} | ${pct(counts.quota, total)} |\n| Max-turns exceeded | ${counts.max_turns} | ${pct(counts.max_turns, total)} |\n| REFINE cycles (retried) | ${counts.refined} | ${pct(counts.refined, total)} |\n| Audit log missing | ${counts.missing} | ${pct(counts.missing, total)} |\n\n### Token usage\n\n${tokenSection}\n\n_Generated by Hall stability reporter. [View run](https://github.com/${REPO}/actions/runs/${RUN_ID})_`
}

function main() {
  const runs = listRuns()
  if (!runs.length) { console.log('No runs found — skipping report.'); return }

  mkdirSync(TMP, { recursive: true })

  const counts = { success: 0, failed: 0, quota: 0, max_turns: 0, refined: 0, missing: 0 }
  const dates = []
  let tokenInput = 0, tokenOutput = 0, tokenCount = 0

  for (const run of runs) {
    dates.push(run.createdAt)
    const log = fetchLog(run.databaseId)
    counts[classify(log)]++
    if (log && (log.token_input || 0) > 0) {
      tokenInput += log.token_input
      tokenOutput += (log.token_output || 0)
      tokenCount++
    }
  }

  rmSync(TMP, { recursive: true, force: true })

  const body = buildBody(counts, runs.length, dates, tokenInput, tokenOutput, tokenCount)
  const month = new Date().toLocaleString('default', { month: 'long', year: 'numeric' })

  gh('issue', 'create', '--repo', REPO,
    '--title', `[Hall] Stability Report — ${month}`,
    '--body', body)

  console.log(`Stability report posted for ${month}.`)
}

main()
